mail: # 邮箱名
password: # 邮箱SMTP密码（非登陆密码）
host: # 邮箱域名（例：smtp.163.com）

---

username: # 我在校园登陆名（一般为手机号）
password: # 登录密码
address: # 居住地址（怡园，憬园等）
receive: # 接收邮箱地址
health: 0 # （是否健康打卡，0否，1是）
daily: 
  - 0 #（是否早检）
  - 0 #（是否午检）
  - 1 #（是否晚检）

--- # 多用户信息配置请用三个短横线隔开

username: # 我在校园登陆名（一般为手机号）
password: # 登录密码
address: # 居住地址（怡园，憬园等）
receive: # 接收邮箱地址
health: 1 # （是否健康打卡，0否，1是）
daily: 
  - 1 #（是否早检）
  - 1 #（是否午检）
  - 1 #（是否晚检）